### PR TITLE
Remove HttpClient from demos

### PR DESCRIPTION
**Pull request by SimonCropp**
i dont think any of the demos do http requests?

### CODE REVIEW

**Comment by stsrki** [comment]
I would leave just this. The original idea was to have some mockup rest API that would be used from the demo app as an example for users and for internal testing.

**Comment by SimonCropp** [comment]
in that case the code is flawed, since it should be using the IHttpClientFactory  abstraction

**Comment by stsrki** [comment]
Yep. It's an old code when Blazor was young and people still haven't figured that IHttpClientFactory is that way to go.

**Comment by SimonCropp** [comment]
so given the current code is flawed, and trivial to re-add the correct implementation, my recommendation is to remove for now

**Comment by stsrki** [comment]
I agree. Removing it!

**Pull request merged**
