### PR TITLE
DataGrid: edit item creator

### PR DESCRIPTION
**Pull request by puschie286**
Add a callback for creating a new instance on editing to ensure nested object lifecycle

### CODE REVIEW

**Comment by stsrki** [comment]
Looking good to me. @David-Moreira any comment?

**Comment by David-Moreira** [comment]
It's a nice idea for one of datagrid's limitations. 
Might provoke unexpected behaviours if we like provide an entirelly new object for example? Other than that, looks good.

**Comment by stsrki** [comment]
Yeah, as long as the item reference stays the same I think it should be good. We need to document it so that people are aware of it.

**Comment by stsrki** [comment]
Sorry, it took me too long to respond. Thank you for the PR!

**Pull request merged**
