### PR TITLE
DataGridColumn | HelpText

### PR DESCRIPTION
**Pull request by David-Moreira**

### CODE REVIEW

**Comment by stsrki** [comment]
I get this when I start the demo

image

**Comment by David-Moreira** [comment]
> I get this when I start the demo
> 
> image

You need to jump that exception or comment the faulty code. 
It's a bug I introduced recently: https://github.com/Megabit/Blazorise/issues/5098

**Comment by stsrki** [comment]
> > I get this when I start the demo
> > image
> 
> You need to jump that exception or comment the faulty code. It's a bug I introduced recently: #5098

OK please fix that in 1.3 so that we can bring it forward into the master branch.

**Comment by stsrki** [comment]
There are duplicates on edit form

image

image

**Comment by David-Moreira** [comment]
No idea, I'll have to take a look.

**Comment by David-Moreira** [comment]
> There are duplicates on edit form
> 
> image
> 
> image

hmm I kinda had the logic all around. I centralized it on the `_DataGridCell` internal component instead. Should be good now.

**Comment by David-Moreira** [comment]
@stsrki please review again

**Comment by David-Moreira** [comment]
@stsrki bump

**Review by stsrki — APPROVED** [review]

**Pull request merged**
