### PR TITLE
SignaturePad: fix aspect ratio

### LINKED ISSUE #5411: [Bug]: SignaturePad - fromUrl - Resizing image
### Blazorise Version

1.5.0

### What Blazorise provider are you running on?

Bootstrap5

### Link to minimal reproduction or a simple code snippet

https://bootstrap5demo.blazorise.com/tests/signaturepad 

watch the canvas and the preview

### Steps to reproduce

1) browse to https://bootstrap5demo.blazorise.com/tests/signaturepad 
2) draw on the canvas 

### What is expected?

the canvas image is the same as what was drawn on the canvas.

### What is actually happening?

the canvas image is resized larger.

### What browsers do you see the problem on?

Chrome

### Any additional comments?

_No response_

### PR DESCRIPTION
**Pull request by sks-ttaylor**
## Description

Closes #5411

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality not to work as expected)

## Checklist:

- [x] The PR is submitted to the correct branch (`master` for dev, `rel-1.x` for maintenance).
- [ ] My code follows the code style of this project.
- [ ] I've added relevant tests.

### CODE REVIEW

**Comment by stsrki** [comment]
Hey @sks-ttaylor, can you explain how you tested it? I'm trying to reproduce it, and as far as I can see, there are no differences in behavior between this and the previous version.

- What browser?
- Mobile or desktop mode?

**Comment by sks-ttaylor** [comment]
I am using Chrome version 123.0.6312.59 (Official Build) (64-bit)

Desktop

browsing to https://bootstrap5demo.blazorise.com/tests/signaturepad

what I see:

[cid:1d016b06-ec07-4b12-8886-6f51102dd798]
________________________________

**Comment by stsrki** [comment]
OK so I have updated to the latest Chrome Version 123.0.6312.59 (Official Build) (64-bit). The first thing I noticed it became much ugly than before 😥

---

But the signature pad still seems to work the same in the old and new versions.

image

I made sure to clear the cache at all times.

**Comment by sks-ttaylor** [comment]
I am unsure what to tell you.

I just clear my cache, confirmed via browser debug that the v1.5.0 signaturepad.js is loading

drew on the canvas

Got the following:
[cid:6f8f173c-5622-42f3-a241-0a68ab3be81c]

also noticed that if you click on the canvas, it will resize the canvas.

after one click on the canvas:

[cid:552d7f00-46f0-4222-b86d-cce4af8a108f]

________________________________

**Comment by stsrki** [comment]
@David-Moreira can you try it on your side also?

**Review by stsrki — APPROVED** [review]
I'm moving forward and merging the PR. From my tests, there are no issues, although I cannot reproduce the original problem. And if the fix works for other people, then all the better.

@sks-ttaylor Thank you for the contribution.

**Pull request merged**
