### PR TITLE
QRCode component

### LINKED ISSUE #3410: Feature - QR-Code extension
Component for generating QR codes based on something like

https://github.com/codebude/QRCoder

    <Blazorise.QRCode Text="https://blazorise.com" ECCLevel="L" EciMode="Default" DarkColor="Black" LightColor="White" />

or
   
    <Blazorise.QRCode ECCLevel="L" EciMode="Default" DarkColor="Black" LightColor="White">
        https://blazorise.com
    </Blazorise.QRCode>

### PR DESCRIPTION
**Pull request by stsrki**
closes #3410

### CODE REVIEW

**Comment by njannink** [comment]
Good @stsrki  I didn't have time yet to add documentation

**Comment by stsrki** [comment]
I was also thinking about removing the Anchor logic. Users can always just use the existing `Link` or `Achor` component to wrap the `QRCode`.

**Comment by stsrki** [comment]
OK, I have removed the Anchor flag. Now it will only generate images.

**Comment by njannink** [comment]
Thanks for your help @stsrki with getting this component integrated

**Comment by stsrki** [comment]
Thank you for making it in the first place. It was practically done already. Just needed a small tweeks.

**Pull request merged**
