### PR TITLE
Add Blazorise Google Captcha to HelpUsImprove & Contact Pages

### PR DESCRIPTION
**Pull request by David-Moreira**

### CODE REVIEW

**Comment by David-Moreira** [comment]
@stsrki Let's use our own implementation to handle this.

When implementing it, I kinda wish we had a better integration with the validation system, what do you think?

**Review by stsrki — COMMENTED** [review]
Wouldn't it be better to create something like a `CaptchaInput` component and bind the result to a variable. eg.

```
<CaptchaInput @bind-Value="captchaValid" />
```

It is a lot easier to handle it then inheriting from a base page class.

**Comment by David-Moreira** [comment]
> Wouldn't it be better to create something like a `CaptchaInput` component and bind the result to a variable. eg.
> 
> ```
> <CaptchaInput @bind-Value="captchaValid" />
> ```
> 
> It is a lot easier to handle it then inheriting from a base page class.

I guess you're right, it'll be better. I'll make that change.

**Comment by David-Moreira** [comment]
@stsrki Well... "alot easier" I guess the correct word is "more elegant", because it did take me substiantly more time to implement it properly haha. 
I made use of `BaseInputComponent` abstraction and some of the code from the `Check` so we can have proper blazorize validation support. Please check whether it's well implemented as I'm not well versed in these apis.

**Review by stsrki — APPROVED** [review]
LGTM

**Comment by stsrki** [comment]
You did such a great work that it is worth making a blog #5403

🤣

**Pull request merged**
