### PR TITLE
Datagrid : Arrow up | Arrow Down | Enter Support

### LINKED ISSUE #3665: DataGrid : ArrowUp/ArrowDown selection support
DataGrid : ArrowUp/ArrowDown selection support

https://media.giphy.com/media/2P8lemvuZiCeDMcMZc/giphy.gif

sample code:
```
@code {

    [Inject] EmployeeData EmployeeData { get; set; }

    private IEnumerable<Employee> inMemoryData;
    [Inject] IJSRuntime JSRuntime { get; set; }
    private DataGrid<Employee> _dataGridRef;
    public Employee SelectedRow { get; set; }
    private DotNetObjectReference<Dashboard>? dotNetObject;

    protected override async Task OnInitializedAsync()
    {
        dotNetObject = DotNetObjectReference.Create(this);
        inMemoryData = (await EmployeeData.GetDataAsync().ConfigureAwait(false)).Take(25);
        await base.OnInitializedAsync();
    }

    protected override async Task OnAfterRenderAsync(bool firstRender)
    {
        if (firstRender)
        {
            await JSRuntime.InvokeVoidAsync("InitializeDataGridKeyDownListener", dotNetObject, _dataGridRef.ElementId);
        }
        await base.OnAfterRenderAsync(firstRender);
    }

    [JSInvokable]
    public Task OnArrowDown()
    {
        Console.WriteLine("OnArrowDown");
        var idx = _dataGridRef.DisplayData.ToList().IndexOf(SelectedRow);
        if (idx < _dataGridRef.DisplayData.Count())
        {
            return _dataGridRef.Select(_dataGridRef.DisplayData.ElementAt(idx + 1));
        }
        return Task.CompletedTask;
    }

    [JSInvokable]
    public Task OnArrowUp()
    {
        Console.WriteLine("OnArrowUp");
        var idx = _dataGridRef.DisplayData.ToList().IndexOf(SelectedRow);
        if (idx > 0)
        {
            return _dataGridRef.Select(_dataGridRef.DisplayData.ElementAt(idx - 1));
        }
        return Task.CompletedTask;
    }

}
function InitializeDataGridKeyDownListener(dotNetObject, elementId) {
    var dotNetInstance = dotNetObject;
    document.getElementById(elementId).querySelectorAll('tr').forEach(x => {
        x.setAttribute("tabindex", 0); //Element needs to be focusable
        x.addEventListener("keydown", function (e) {
            if (e.key == "ArrowUp") {
                dotNetInstance.invokeMethodAsync("OnArrowUp");
            }

                if (e.key == "ArrowDown") {
                    dotNetInstance.invokeMethodAsync("OnArrowDown");
                }
        });
    });
}
```

### PR DESCRIPTION
**Pull request by David-Moreira**
Closes #3665

Works pretty good, let me know if you agree with the approach.

### CODE REVIEW

**Review by stsrki — COMMENTED** [review]
It works well, feature-wise. But, it needs to be an opt-in feature.

Add `bool Navigable` on the DataGrid level, and if enabled, the user can navigate with the keyboard.

Also, can we remove the border around selected row that shows when `tabindex="0"`?

**Comment by David-Moreira** [comment]
> It works well, feature-wise. But, it needs to be an opt-in feature.
> 
> Add `bool Navigable` on the DataGrid level, and if enabled, the user can navigate with the keyboard.
> 
> Also, can we remove the border around selected row that shows when `tabindex="0"`?

Well I tought about it, but ended up thinking we might want it to be part of regular Datagrid functionalities.
Then I'll make the new parameter.

**Comment by David-Moreira** [comment]
> Also, can we remove the border around selected row that shows when `tabindex="0"`?

Part of the feature, was that you could tab, and press Enter to Select the Rows, if you disable the border you don't know where you're tabbing?

**Comment by stsrki** [comment]
> Part of the feature, was that you could tab, and press Enter to Select the Rows, if you disable the border you don't know where you're tabbing?

You know because the row is selected and has a selected color.

**Comment by stsrki** [comment]
Is there a way to prevent browser from scrolling the page when we navigate the grid with arrows?

**Comment by David-Moreira** [comment]
> > Part of the feature, was that you could tab, and press Enter to Select the Rows, if you disable the border you don't know where you're tabbing?
> 
> You know because the row is selected and has a selected color.

So if you want to select a row 3 arrows below the one selected you should count 3 tabs and click enter without any feedback at all?

**Comment by David-Moreira** [comment]
> Is there a way to prevent browser from scrolling the page when we navigate the grid with arrows?

No idea, I can try investigating.

**Review by stsrki — APPROVED** [review]

**Pull request merged**
