### PR TITLE
Add ProductToken to BlazoriseOptions

### LINKED ISSUE #4712: ProductToken in BlazoriseOptions
We need to introduce new **ProductToken** in **BlazoriseOptions**. And make **LicenseKey** property obsolete.

### PR DESCRIPTION
**Pull request by stsrki**
Closes #4712

### CODE REVIEW

**Comment by David-Moreira** [comment]
LGTM, doesn't seem like you've missed anything.
I was just thinking from looking at the code, do we actually stop the background worker / dispose of it? Would that not be interesting?

**Comment by stsrki** [comment]
As far as I know, it stops by itself. It is a fire once operation.

**Comment by David-Moreira** [comment]
> As far as I know, it stops by itself. It is a fire once operation.

Maybe I'm confusing with some other api? I was under the impression it would keep calling back until you explicitly tell it to stop. otherwise why would you have the initialized flag checked if it's one time run?

**Comment by David-Moreira** [comment]
Well it does seem to be one time only from the docs, so nvm, I must be confusing.
image

Thanks.

**Comment by David-Moreira** [comment]
I was confusing with this one:
https://learn.microsoft.com/en-us/aspnet/core/fundamentals/host/hosted-services?view=aspnetcore-7.0&tabs=visual-studio

image

**Comment by stsrki** [comment]
I think I tried that. But WASM has limited support for async code during the startup. That's why I had to fallback into the old BackgroundWorker

**Pull request merged**
