### PR TITLE
Corrected two dutch translation which made no sense

### PR DESCRIPTION
**Pull request by joost00719**

### CODE REVIEW

**Comment by joost00719** [comment]
"duidelijk" technically means "clear", but it means something more close to "understood".
I change it to "Reset", which also means "reset" in english. There is no good translation which goes for "clear", but "reset" fits the context better.

**Comment by joost00719** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by David-Moreira** [comment]
@joost00719 can you check that your github registered email is the same you've used for your commit? 
image

**Comment by joost00719** [comment]
@David-Moreira  I have resolved the check issues

**Review by stsrki — APPROVED** [review]
LGTM. Thank you!

**Pull request merged**
