### PR TITLE
Fix closable.js find index functions.

### LINKED ISSUE #4379: Modals not closing when clicked on backdrop
This only happens when more than one modal is opened.

To reproduce, go to https://bootstrapdemo.blazorise.com/tests/modals

1. Open any modal
2. Click on the `Show second modal` button
3. Click on the backdrop
4. After the second modal closes, click on the backdrop again

The modal should be closed.

### PR DESCRIPTION
**Pull request by Bobbar**
Found a bug introduced in 35849a17.   Fixes #4379. 

I imagine this may have caused issues elsewhere as well.

### CODE REVIEW

**Comment by David-Moreira** [comment]
That's awesome @Bobbar thanks for helping us solve the problem. We'll have to take a look at what side effects it can have now, since it was probably changed for some reason.

Can I ask you that you re-target **rel-1.1** instead of master.

**Comment by Bobbar** [comment]
Of course, my bad. 🤦

Should I create a new PR or just change the base? rel-1.1 is a ways behind master.

**Comment by David-Moreira** [comment]
Right, master has ongoing work for the next release.

You should have branched from **rel-1.1**. Since this is a fix intended for our current **v1.1** release. If you could go ahead and do that we'd appreciate it. You may close this PR in favor of the new one.

**Comment by Bobbar** [comment]
Hmm. For some reason I can't see rel-1.1 and a few other branches in my fork.

I'll revisit this in the next few days and fix it up.

**Comment by stsrki** [comment]
> Hmm. For some reason I can't see rel-1.1 and a few other branches in my fork.
> 
> I'll revisit this in the next few days and fix it up.

You can easily update your fork from GH UI.

image

**Comment by Bobbar** [comment]
Closing to fix target base.

**Pull request closed without merging**
