### PR TITLE
ThemeProvider: Fix generator for Bar background color

### LINKED ISSUE #5188: [Bug]: Ant Design Bar background does not work on sider bar
### Blazorise Version

1.4

### What Blazorise provider are you running on?

AntDesign

### Link to minimal reproduction, or a simple code snippet

https://github.com/KyleTraynor/BlazoriseAntBug

### Steps to reproduce

Create a new project in visual studio using Blazorise App (MegaBit). choose Ant Design for the provider.

Add this code to the theme:

```
BarOptions = new ThemeBarOptions
{
    HorizontalHeight = "64px",
    DarkColors = new ThemeBarColorOptions
    {
        BackgroundColor = "#ff0000",
        Color = "#ff0000",
        ItemColorOptions = new ThemeBarItemColorOptions
        {
            ActiveBackgroundColor = "#ff0000",
            ActiveColor = "#ff0000",
            HoverBackgroundColor = "#ff0000",
            HoverColor = "#ff0000",
        }
    },
},
```

### What is expected?

Bar background should be red.

### What is actually happening?

Bar background does not change.

### What browsers are you seeing the problem on?

_No response_

### Any additional comments?

It works with the bootstrap provider, but not with the ant design provider.

### PR DESCRIPTION
**Pull request by steal4life**
closes #5188 

Here, I have tried everything I know to fix it, so when I put these classes in the theme provider, they are not added, even though by all logical parameters they should be added to the ant-menu... when I manually add these same classes inside scss -a, everything works without problems, take a look and give me some advice because I really don't see what the problem is with this approach

### CODE REVIEW

**Comment by steal4life** [comment]
p.s.

Add this to App.razor(in demo folder)

        Enabled = true,
            BarOptions = new()
            {
                HorizontalHeight = "72px",
                DarkColors = new ThemeBarColorOptions
                {
                    BackgroundColor = "#ff0000",
                    Color = "#ff0000",
                    ItemColorOptions = new ThemeBarItemColorOptions
                    {
                        ActiveBackgroundColor = "#ff0000",
                        ActiveColor = "#ff0000",
                        HoverBackgroundColor = "#ff0000",
                        HoverColor = "#ff0000",
                    }
              },
         },
         
         just to se what the problem is

**Comment by stsrki** [comment]
Seems to be working fine on my end. I assume the problem is in VS2022 Preview. I sometime also happen to have problems with it.

**Comment by David-Moreira** [comment]
> Seems to be working fine on my end. I assume the problem is in VS2022 Preview. I sometime also happen to have problems with it.

I don't follow, what has vs2022 preview to do with this PR changes?

**Review by David-Moreira — APPROVED** [review]
LGTM,
seems like the recommended way to add the css var with defaults in Blazorise.
@stsrki please validate.

**Comment by stsrki** [comment]
> > Seems to be working fine on my end. I assume the problem is in VS2022 Preview. I sometime also happen to have problems with it.
> 
> I don't follow, what has vs2022 preview to do with this PR changes?

Recently I have problems with VS. After I made some changes in the code and rebuilt to launch the demo app those changes are not applied and I have to restart VS and rebuild again.

**Review by stsrki — APPROVED** [review]

**Pull request merged**
