### PR TITLE
Parametric column items size when tabs are vertical left or right left

### PR DESCRIPTION
**Pull request by cesaremarasco**
Now can be changed the column items size, with a specified param, when tabs are vertical left or right left

### CODE REVIEW

**Comment by stsrki** [comment]
@cesaremarasco Can you please switch your work to dev093 branch before I review the code?

**Comment by cesaremarasco** [comment]
> @cesaremarasco Can you please switch your work to dev093 branch before I review the code?
Done  !

**Comment by stsrki** [comment]
🤔 I don't see any changes!

**Comment by cesaremarasco** [comment]
> 🤔 I don't see any changes!

Sorry but, i had pushed inside a branch under my Fork. If i try tu push inside dev03 of main project i receive

Opening repositories:
Pushing dev093
Remote: Permission to stsrki/Blazorise.git denied to cesaremarasco.
Error encountered while pushing to the remote repository: Git failed with a fatal error.
unable to access 'https://github.com/stsrki/Blazorise.git/': The requested URL returned error: 403

**Comment by stsrki** [comment]
In that case, I might reproduce PR manually. It's not that dificult.

**Comment by cesaremarasco** [comment]
> In that case, I might reproduce PR manually. It's not that dificult.

The change is basically very simple but i think powefull for my case but i think for everyone as-well. I added a new property for Tabs control

   [Parameter] public IFluentColumn ColumnItemsSize { get; set; } = ColumnSize.IsAuto;

and than inside View

```
else if ( TabPosition == TabPosition.Left )
        {
            <Row>
                <Column ColumnSize="ColumnItemsSize">
                    @if ( Items != null )
                    {
                        <ul class="@ClassNames" style="@StyleNames" @attributes="@Attributes">
                            @Items
                        </ul>
                    }
                </Column>
                <Column>
                    @if ( Content != null )
                    {
                        <div class="@ContentClassNames" @attributes="@Attributes">
                            @Content
                        </div>
                    }
                </Column>
            </Row>
        }
        else if ( TabPosition == TabPosition.Right )
        {
            <Row>
                <Column>
                    @if ( Content != null )
                    {
                        <div class="@ContentClassNames" @attributes="@Attributes">
                            @Content
                        </div>
                    }
                </Column>
                <Column ColumnSize="ColumnItemsSize">
                    @if ( Items != null )
                    {
                        <ul class="@ClassNames" style="@StyleNames" @attributes="@Attributes">
                            @Items
                        </ul>
                    }
                </Column>
            </Row>

```
In this way the column width could be parametrized.  I have also added the working example inside application demo. That's all !

**Comment by stsrki** [comment]
@cesaremarasco I'm sorry it took me so long. I took your PR and recreated it as part of #2878.

Thank you!

**Pull request closed without merging**
