### PR TITLE
DataGrid : Handle SelectionMode Changed

### LINKED ISSUE #2549: DataGrid Selection Behavior on Switching Single / Multiple
I made a little recording, for repro (using https://bootstrapdemo.blazorise.com/tests/datagrid):

* In single mode, select an item
* Switch to multiple; it seems that the selection carried over.
* Click on any other item - you now see that the selected item wasn't actually selected because now only the newly selected item is so.

The bound data is ok, but the UI doesn't seem to catch on.

Animation

### PR DESCRIPTION
**Pull request by David-Moreira**
Fixes #2549

### CODE REVIEW

**Comment by David-Moreira** [comment]
Hey @stsrki 
I don't think this was picked up for dev094

**Comment by David-Moreira** [comment]
@stsrki ? :P

**Comment by stsrki** [comment]
Cherry picked? Might be I forgot or I failed to understand you, thinking it was already fixed in 0.9.4.

**Comment by stsrki** [comment]
Can you include it in your Virtualize branch?

**Comment by David-Moreira** [comment]
Done.

**Pull request merged**
