### PR TITLE
Feature/fix icelandic translations

### PR DESCRIPTION
**Pull request by sturlath**
Here are some changes from me for Icelandic. Sorry I didn´t realise I was on master so this draft has the previous ShakaPlayer PR also. I hope you can cherry pick out of this or just copy paste the changes..

### CODE REVIEW

**Comment by stsrki** [comment]
No worries. I will copy changes manually.

Thank you!

**Comment by stsrki** [comment]
Fixed as part of #3283

**Comment by sturlath** [comment]
Hi @stsrki  I had also fixed ColorPicker and DataGrid that had just awful translations ;-) but you did not pick those out of the PR

**Comment by stsrki** [comment]
🤦‍♂️ I was so focused on datepicker that I completely overlooked other components. No worries. I will make it happen for the next release.

**Pull request closed without merging**
