### PR TITLE
Fix antdesign switch

### PR DESCRIPTION
**Pull request by Magehernan**
Re open wit changes on rel-1.1

### CODE REVIEW

**Comment by Magehernan** [comment]
@stsrki hi here it is, i tested and continue working... i not sure if the pull request is ok, let me know.

Thanks

**Comment by Magehernan** [comment]
mmm i think i rebase my branch on rel-1.2 so maybe i make this pull request wrong.

**Comment by stsrki** [comment]
> mmm i think i rebase my branch on rel-1.2 so maybe i make this pull request wrong.

Yeah, I think you should open a new branch :) Closing this now.

**Comment by stsrki** [comment]
PS. We are already checking the value in the base `Switch.razor.cs` in the core project.

So I think this change should also work

```
/// <inheritdoc/>
public override async Task SetParametersAsync( ParameterView parameters )
{
    if ( Rendered )
    {
        if ( parameters.TryGetValue<TValue>( nameof( Checked ), out var paramChecked ) && !paramChecked.IsEqual( Checked ) )
        {
            ExecuteAfterRender( async () =>
            {
                await Revalidate();

                DirtyClasses();
                await InvokeAsync( StateHasChanged );
            } );
        }
    }

    await base.SetParametersAsync( parameters );

    if ( ParentValidation != null )
    {
        if ( parameters.TryGetValue<Expression<Func<TValue>>>( nameof( CheckedExpression ), out var expression ) )
            await ParentValidation.InitializeInputExpression( expression );

        await InitializeValidation();
    }
}
```

**Pull request closed without merging**
