### PR TITLE
PagerAlignment - CherryPick for correct branch history

### PR DESCRIPTION
**Pull request by David-Moreira**
#2491

#2480 Pagination Items not aligned straight in DataGrid

### CODE REVIEW

**Comment by David-Moreira** [comment]
hmm keeps doing the same, as if those two commits were missing from sup093.

**My Branch History:**
image

**Comment by stsrki** [comment]
Did you update your sup093 branch before creating new feature branch?

**Comment by David-Moreira** [comment]
Yea, it actually comes from the merge.
image
image

**Comment by stsrki** [comment]
Strange. No worries then. I will merge it anyways after I test it. Thanks!

**Comment by David-Moreira** [comment]
Thanks

**Pull request merged**
