### PR TITLE
File Scoped Namespaces

### PR DESCRIPTION
**Pull request by SimonCropp**

### CODE REVIEW

**Comment by stsrki** [comment]
That's a lot of changes. My browser almost can't handle it 😅. As far as I can see, it looks good. 

PS. can you please accept the CLA before merging?

**Comment by stsrki** [comment]
We need to be careful with the merge. `rel-1.0` and `rel-1.1` are still unformatted, and since we regularly merge fixes back to `master,` there will be conflicts.

**Comment by stsrki** [comment]
TODO: add rule to editorconfig https://stackoverflow.com/questions/69889519/vs-2022-convert-to-file-scoped-namespace-in-all-files

**Comment by David-Moreira** [comment]
Also LGTM. There's not much to review here. :)
@stsrki would it be easier to target rel1.1 and merge from there?

**Comment by stsrki** [comment]
> would it be easier to target rel1.1 and merge from there?

I'm tempted, but better to move forward from the master.

**Comment by SimonCropp** [comment]
happy to re-target any branch. just let me know

**Comment by stsrki** [comment]
> happy to re-target any branch. just let me know

No need to retarget. Well' make it on this branch. @SimonCropp Can you please accept the CLA? See the comment above.

**Comment by SimonCropp** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by SimonCropp** [comment]
i think i addresses everything

**Comment by stsrki** [comment]
@SimonCropp All done. Thank you!

**Pull request merged**
