### PR TITLE
Player controls of video component

### PR DESCRIPTION
**Pull request by foster066**
Add ability to provide the list of rendered controls on the plyr video player.
The list of controls are provided in the VideoControlsType static class as string constants and it's based on [plyr documentation](https://github.com/sampotts/plyr/blob/master/CONTROLS.md).

### CODE REVIEW

**Comment by foster066** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by foster066** [comment]
recheck

**Comment by foster066** [comment]
recheck

**Comment by foster066** [comment]
recheck

**Review by stsrki — APPROVED** [review]
Added a default list of controls based on the plyr documentation. Other that than, good PR. Thanks for your contribution.

**Pull request merged**
