### PR TITLE
show snapshot testing approach

### PR DESCRIPTION
**Pull request by SimonCropp**
thoughts?

### CODE REVIEW

**Comment by David-Moreira** [comment]
Hello @SimonCropp 
I have seen your presentation on "BlazorTrain" about Verify. It's pretty cool indeed, congrats. We'll take a look at your suggestion. Thanks! :D

**Comment by stsrki** [comment]
Hi, @SimonCropp Thank you for taking the time to implement it in Blazorise. I hate to say it, but can I ask you to recreate PR on the **dev094** branch. We generally don't accept any new work on the `master` branch since it can lead to problems once we merge all dev work for the final release. And considering the master and dev branches are already very different it would be hard for us to maintaining it even as it is.

Once you finish we'll gladly test it. Thank you!

**Comment by SimonCropp** [comment]
will do

**Comment by stsrki** [comment]
I have tried tests and they're working. But there is a problem. I tried to first format HTML, eg. `ButtonComponentTest.RenderTest.01.verified.html` and then run the test. Tests fail because the strings don't match while I was expecting it to compare the HTML structure. Is this the expected behavior?

**Pull request closed without merging**
