### PR TITLE
DataGrid : Groupable | Expand or collapse specific groups by key

### PR DESCRIPTION
**Pull request by David-Moreira**

### CODE REVIEW

**Comment by David-Moreira** [comment]
Better review datagrid.razor.cs from commits, files changed, reports too many changes for some reason... Don't know if it was something with EOL...

**Review by stsrki — COMMENTED** [review]
Maybe add a ToggleGroup(...)

**Comment by stsrki** [comment]
Also, add an example in the documentation, and explain the groupKey parameter.

**Comment by David-Moreira** [comment]
@stsrki Friendly reminder

**Review by stsrki — APPROVED** [review]

**Pull request merged**
