### PR TITLE
Add support for the trendline plugin to Chart extension

### PR DESCRIPTION
**Pull request by ledpup**
Uses chartjs-plugin-trendline (https://github.com/Makanz/chartjs-plugin-trendline) to add linear trendlines to existing datasets in a chart.

### CODE REVIEW

**Comment by stsrki** [comment]
I have no idea what happened but somehow the PR got merged into master 🤔🤔🤔

**Comment by stsrki** [comment]
In any case, you did a good job. I have made some small changes but overall it looks and works well.

Thank you for taking the time to make it happen!

**Comment by ledpup** [comment]
Cool, I'm glad it's in. Do you know roughly when you'll do the next release with the new chartjs version and the trendline nuget?

**Comment by stsrki** [comment]
Final v1.0 should be sometime in February. But I can release a preview even sooner.

**Pull request merged**
