### PR TITLE
Support types without object equal operator ( extend test for DateTime, TimeSpan )

### PR DESCRIPTION
**Pull request by puschie286**
Implement compare for value types.

Add test for DateTime and TimeSpan

### CODE REVIEW

**Comment by David-Moreira** [comment]
So basically this is to access value types within structs? Is that it? 
Can you add more tests for other value types within the struct just to make sure everything works fine?

@stsrki are we doing net6 only on 1.0.0? Maybe we can think about adding the new Date Types in .NET6 to the tests also.

@puschie286 why `Activator` over `Expression.Default`?  Would the later not make more sense and be more performant in these cases? Could you please test?

**Comment by puschie286** [comment]
@David-Moreira its for comparing struct that doesnt have a equal operator which accept objects.
Express.Constant( null ) is a object so it fail for some struct and Expression.Default / Activator always create a valid instance. 
But im not 100% sure if this is how it works internaly - we use a lot of TimeSpan objects, which caused the expression to fail, so this is what i came up with^^

you are right with Expression.Default, thanks for pointing that out :)

replaced the reflection approach with your suggested expression approach

**Comment by David-Moreira** [comment]
Way simpler change, makes more sense. If all tests are passing, LGTM.
(Do take note, that you're merging this in for 1.0.0, this change would only be live in a few months.)

@stsrki  wanna consider this for 0.9.5? Seems worthy honestly.

**Comment by stsrki** [comment]
@David-Moreira Yeah, it is not breaking any API so it can be done as part of 095. LGTM

**Pull request merged**
