### PR TITLE
Docs : MarkdownShortcutsExample | Fix shortcut example

### PR DESCRIPTION
**Pull request by David-Moreira**

### CODE REVIEW

**Comment by stsrki** [comment]
Any reason why targeting 1.2 branch and not 1.3?

**Comment by David-Moreira** [comment]
Aren't we still releasing and updating v1.2 branch for docs?

**Comment by David-Moreira** [comment]
Is that not the point of 
image
? Do you not compile the docs from 1.2 branch?

**Comment by stsrki** [comment]
No. It is frozen now. It is only accessible in case that someone hasn't updated to 1.3 yet.

**Comment by David-Moreira** [comment]
> No. It is frozen now. It is only accessible in case that someone hasn't updated to 1.3 yet.

I thought it'd make sense to fix any simple docs issue like this one in 1.2 and propagate through the code base. if it's frozen, let's retarget 1.3 then.

**Comment by David-Moreira** [comment]
Ah jesus christ. Retarget made a mess. I'm just going to remake the PR. Closing...

**Pull request closed without merging**
