### PR TITLE
Use catch when

### PR DESCRIPTION
**Pull request by SimonCropp**
to avoid the catch and re-throw when !task.IsCanceled

so we only swallow  when ( task.IsCanceled )

### CODE REVIEW

**Comment by David-Moreira** [comment]
It is of note that this is "syntactic sugar", right? It should still be lowered and compiled to IL as a simple if.

**Comment by SimonCropp** [comment]
my understanding it is not "just syntactic sugar" https://ivanderevianko.com/2015/05/c-6-0-exception-filters-try-catch-when

**Comment by SimonCropp** [comment]
and another one http://www.volatileread.com/Wiki/Index?id=1087

**Comment by stsrki** [comment]
I remember we had a valid reason why we re-throw an error but I can't find the original issue now.  It was something about tasks being timeout after one minute.

@David-Moreira do you remember it maybe?

**Comment by David-Moreira** [comment]
Nice. I'll read those posts later. I skimmed through the first one I saw it has the compiled IL, great! 

Strski, 
I think it had to do with blazor throwing task cancelled to us on the disposal process. And we were letting it bubble up. I'll see if I can find the thread also.

Simons solution should be equivalent to what we had. It might be even better if it produces improved IL i thought it would produce the same behind the covers, apparently maybe not.

**Comment by stsrki** [comment]
Based on those two articles seems to me also that this feature is a nice optimization. From what I can understand, if an error happens it will re-throw for all situations except for when the Task is canceled. Basically what we already do, but better.

**Comment by David-Moreira** [comment]
Yea, pretty good feature, not just "syntactic sugar".  
And apparently it doesn't "re-throw", it's not even caught if it doesn't meet the "filter"(condition) to begin with.
Awesome! 👍

**Pull request merged**
