### PR TITLE
Internals: Safer JS invocations and exception handling

### LINKED ISSUE #4723: Docs: errors with JS Interop
I assume the error is happening because the user is having an older `blazorise.docs.js` file cached.

```
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Production
info: Microsoft.Hosting.Lifetime[0]
      Content root path: C:\WEB\sites\blazorise.com\www
Cancel Clicked
fail: Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost[111]
      Unhandled exception in circuit 'bEXYd-0-w-kfvIBiz9l1fseMXPWckwg5RuH2f1wdD_w'.
      System.Threading.Tasks.TaskCanceledException: A task was canceled.
         at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
         at Microsoft.JSInterop.JSRuntimeExtensions.InvokeVoidAsync(IJSRuntime jsRuntime, String identifier, Object[] args)
         at Blazorise.Docs.Layouts.DocsLayout.OnLocationChanged(Object sender, LocationChangedEventArgs e) in D:\Projects\UI\Blazorise\Documentation\Blazorise.Docs\Layouts\DocsLayout.razor.cs:line 60
         at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
         at Microsoft.AspNetCore.Components.Rendering.RendererSynchronizationContext.ExecuteSynchronously(TaskCompletionSource completion, SendOrPostCallback d, Object state)
         at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
      --- End of stack trace from previous location ---
         at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
         at Microsoft.AspNetCore.Components.Rendering.RendererSynchronizationContext.ExecuteBackground(WorkItem item)
warn: Microsoft.AspNetCore.Components.Server.Circuits.RemoteRenderer[100]
      Unhandled exception rendering component: Could not find 'blazoriseDocs.navigation.generateToc' ('blazoriseDocs' was undefined).
Error: Could not find 'blazoriseDocs.navigation.generateToc' ('blazoriseDocs' was undefined).
    at https://blazorise.com/_framework/blazor.server.js:1:497
    at Array.forEach (<anonymous>)
    at s.findFunction (https://blazorise.com/_framework/blazor.server.js:1:465)
    at E (https://blazorise.com/_framework/blazor.server.js:1:2611)
    at https://blazorise.com/_framework/blazor.server.js:1:3499
    at new Promise (<anonymous>)
    at Ft.beginInvokeJSFromDotNet (https://blazorise.com/_framework/blazor.server.js:1:3480)
    at Ft._invokeClientMethod (https://blazorise.com/_framework/blazor.server.js:1:75072)
    at Ft._processIncomingData (https://blazorise.com/_framework/blazor.server.js:1:72696)
    at Ft.connection.onreceive (https://blazorise.com/_framework/blazor.server.js:1:67009)
      Microsoft.JSInterop.JSException: Could not find 'blazoriseDocs.navigation.generateToc' ('blazoriseDocs' was undefined).
Error: Could not find 'blazoriseDocs.navigation.generateToc' ('blazoriseDocs' was undefined).
    at https://blazorise.com/_framework/blazor.server.js:1:497
    at Array.forEach (<anonymous>)
    at s.findFunction (https://blazorise.com/_framework/blazor.server.js:1:465)
    at E (https://blazorise.com/_framework/blazor.server.js:1:2611)
    at https://blazorise.com/_framework/blazor.server.js:1:3499
    at new Promise (<anonymous>)
    at Ft.beginInvokeJSFromDotNet (https://blazorise.com/_framework/blazor.server.js:1:3480)
    at Ft._invokeClientMethod (https://blazorise.com/_framework/blazor.server.js:1:75072)
    at Ft._processIncomingData (https://blazorise.com/_framework/blazor.server.js:1:72696)
    at Ft.connection.onreceive (https://blazorise.com/_framework/blazor.server.js:1:67009)
         at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
         at Microsoft.JSInterop.JSRuntimeExtensions.InvokeVoidAsync(IJSRuntime jsRuntime, String identifier, Object[] args)
         at Blazorise.Docs.Components.Toc.GenerateToc() in D:\Projects\UI\Blazorise\Documentation\Blazorise.Docs\Components\Toc.razor.cs:line 43
         at Blazorise.Docs.Components.Toc.OnAfterRenderAsync(Boolean firstRender) in D:\Projects\UI\Blazorise\Documentation\Blazorise.Docs\Components\Toc.razor.cs:line 30
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
fail: Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost[111]
      Unhandled exception in circuit 'TRQi_4Q0SL_Kbx7tQZzBTZjSVHJPL_LvCpS88rALtbc'.
      Microsoft.JSInterop.JSException: Could not find 'blazoriseDocs.navigation.generateToc' ('blazoriseDocs' was undefined).
Error: Could not find 'blazoriseDocs.navigation.generateToc' ('blazoriseDocs' was undefined).
    at https://blazorise.com/_framework/blazor.server.js:1:497
    at Array.forEach (<anonymous>)
    at s.findFunction (https://blazorise.com/_framework/blazor.server.js:1:465)
    at E (https://blazorise.com/_framework/blazor.server.js:1:2611)
    at https://blazorise.com/_framework/blazor.server.js:1:3499
    at new Promise (<anonymous>)
    at Ft.beginInvokeJSFromDotNet (https://blazorise.com/_framework/blazor.server.js:1:3480)
    at Ft._invokeClientMethod (https://blazorise.com/_framework/blazor.server.js:1:75072)
    at Ft._processIncomingData (https://blazorise.com/_framework/blazor.server.js:1:72696)
    at Ft.connection.onreceive (https://blazorise.com/_framework/blazor.server.js:1:67009)
         at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
         at Microsoft.JSInterop.JSRuntimeExtensions.InvokeVoidAsync(IJSRuntime jsRuntime, String identifier, Object[] args)
         at Blazorise.Docs.Components.Toc.GenerateToc() in D:\Projects\UI\Blazorise\Documentation\Blazorise.Docs\Components\Toc.razor.cs:line 43
         at Blazorise.Docs.Components.Toc.OnAfterRenderAsync(Boolean firstRender) in D:\Projects\UI\Blazorise\Documentation\Blazorise.Docs\Components\Toc.razor.cs:line 30
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
warn: Microsoft.AspNetCore.Components.Server.Circuits.RemoteRenderer[100]
      Unhandled exception rendering component: tocbot is not defined
ReferenceError: tocbot is not defined
    at Object.generateToc (https://blazorise.com/_content/Blazorise.Docs/blazorise.docs.min.js?v=1.2.2.0:1:468)
    at https://blazorise.com/_framework/blazor.server.js:1:3506
    at new Promise (<anonymous>)
    at Ft.beginInvokeJSFromDotNet (https://blazorise.com/_framework/blazor.server.js:1:3480)
    at Ft._invokeClientMethod (https://blazorise.com/_framework/blazor.server.js:1:75072)
    at Ft._processIncomingData (https://blazorise.com/_framework/blazor.server.js:1:72696)
    at Ft.connection.onreceive (https://blazorise.com/_framework/blazor.server.js:1:67009)
    at i.onmessage (https://blazorise.com/_framework/blazor.server.js:1:51322)
      Microsoft.JSInterop.JSException: tocbot is not defined
ReferenceError: tocbot is not defined
    at Object.generateToc (https://blazorise.com/_content/Blazorise.Docs/blazorise.docs.min.js?v=1.2.2.0:1:468)
    at https://blazorise.com/_framework/blazor.server.js:1:3506
    at new Promise (<anonymous>)
    at Ft.beginInvokeJSFromDotNet (https://blazorise.com/_framework/blazor.server.js:1:3480)
    at Ft._invokeClientMethod (https://blazorise.com/_framework/blazor.server.js:1:75072)
    at Ft._processIncomingData (https://blazorise.com/_framework/blazor.server.js:1:72696)
    at Ft.connection.onreceive (https://blazorise.com/_framework/blazor.server.js:1:67009)
    at i.onmessage (https://blazorise.com/_framework/blazor.server.js:1:51322)
         at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
         at Microsoft.JSInterop.JSRuntimeExtensions.InvokeVoidAsync(IJSRuntime jsRuntime, String identifier, Object[] args)
         at Blazorise.Docs.Components.Toc.GenerateToc() in D:\Projects\UI\Blazorise\Documentation\Blazorise.Docs\Components\Toc.razor.cs:line 43
         at Blazorise.Docs.Components.Toc.OnAfterRenderAsync(Boolean firstRender) in D:\Projects\UI\Blazorise\Documentation\Blazorise.Docs\Components\Toc.razor.cs:line 30
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
fail: Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost[111]
      Unhandled exception in circuit 'eDu6GFFbCAVon-VXX2YRB-TrSUzo3D0x3kPyxe9Rzso'.
      Microsoft.JSInterop.JSException: tocbot is not defined
ReferenceError: tocbot is not defined
    at Object.generateToc (https://blazorise.com/_content/Blazorise.Docs/blazorise.docs.min.js?v=1.2.2.0:1:468)
    at https://blazorise.com/_framework/blazor.server.js:1:3506
    at new Promise (<anonymous>)
    at Ft.beginInvokeJSFromDotNet (https://blazorise.com/_framework/blazor.server.js:1:3480)
    at Ft._invokeClientMethod (https://blazorise.com/_framework/blazor.server.js:1:75072)
    at Ft._processIncomingData (https://blazorise.com/_framework/blazor.server.js:1:72696)
    at Ft.connection.onreceive (https://blazorise.com/_framework/blazor.server.js:1:67009)
    at i.onmessage (https://blazorise.com/_framework/blazor.server.js:1:51322)
         at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
         at Microsoft.JSInterop.JSRuntimeExtensions.InvokeVoidAsync(IJSRuntime jsRuntime, String identifier, Object[] args)
         at Blazorise.Docs.Components.Toc.GenerateToc() in D:\Projects\UI\Blazorise\Documentation\Blazorise.Docs\Components\Toc.razor.cs:line 43
         at Blazorise.Docs.Components.Toc.OnAfterRenderAsync(Boolean firstRender) in D:\Projects\UI\Blazorise\Documentation\Blazorise.Docs\Components\Toc.razor.cs:line 30
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
warn: Microsoft.AspNetCore.Components.Server.Circuits.RemoteRenderer[100]
      Unhandled exception rendering component: JavaScript interop calls cannot be issued at this time. This is because the circuit has disconnected and is being disposed.
      Microsoft.JSInterop.JSDisconnectedException: JavaScript interop calls cannot be issued at this time. This is because the circuit has disconnected and is being disposed.
         at Microsoft.AspNetCore.Components.Server.Circuits.RemoteJSRuntime.BeginInvokeJS(Int64 asyncHandle, String identifier, String argsJson, JSCallResultType resultType, Int64 targetInstanceId)
         at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, CancellationToken cancellationToken, Object[] args)
         at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
         at Microsoft.JSInterop.JSObjectReferenceExtensions.InvokeVoidAsync(IJSObjectReference jsObjectReference, String identifier, Object[] args)
         at Blazorise.LottieAnimation.LottieAnimation.DisposeAnimation() in D:\Projects\UI\Blazorise\Source\Extensions\Blazorise.LottieAnimation\LottieAnimation.razor.cs:line 147
         at Blazorise.LottieAnimation.LottieAnimation.DisposeAsync(Boolean disposing) in D:\Projects\UI\Blazorise\Source\Extensions\Blazorise.LottieAnimation\LottieAnimation.razor.cs:line 134
         at Blazorise.BaseAfterRenderComponent.DisposeAsync() in D:\Projects\UI\Blazorise\Source\Blazorise\Base\BaseAfterRenderComponent.cs:line 136
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.<>c__DisplayClass74_0.<<Dispose>g__HandleAsyncExceptions|1>d.MoveNext()
fail: Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost[111]
      Unhandled exception in circuit '7wdm_t68w2YBr-WJdBG52u-NRgOz36SHLPCOoeWDv5A'.
      Microsoft.JSInterop.JSDisconnectedException: JavaScript interop calls cannot be issued at this time. This is because the circuit has disconnected and is being disposed.
         at Microsoft.AspNetCore.Components.Server.Circuits.RemoteJSRuntime.BeginInvokeJS(Int64 asyncHandle, String identifier, String argsJson, JSCallResultType resultType, Int64 targetInstanceId)
         at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Cance
```

### LINKED ISSUE #5175: [Bug]: Exception logged for tooltip module
### Blazorise Version

1.3.3

### What Blazorise provider are you running on?

Material

### Link to minimal reproduction, or a simple code snippet

From time to time an exception pops up in our application logs around the tooltip module. Probably the exception handling of loading stopped etc should be added

### Steps to reproduce

-

### What is expected?

-

### What is actually happening?

Microsoft.JSInterop.JSException: Failed to fetch dynamically imported module: https://xxx/_content/Blazorise.Material/tooltip.js?v=1.3.3.0
TypeError: Failed to fetch dynamically imported module: https://xxx/_content/Blazorise.Material/tooltip.js?v=1.3.3.0
   at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
   at Blazorise.Modules.BaseJSModule.InvokeSafeVoidAsync(String identifier, Object[] args)
   at Blazorise.Tooltip.<OnInitialized>b__11_0()
   at Blazorise.BaseAfterRenderComponent.OnAfterRenderAsync(Boolean firstRender)
   at Blazorise.BaseComponent.OnAfterRenderAsync(Boolean firstRender)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)

### What browsers are you seeing the problem on?

_No response_

### Any additional comments?

_No response_

### LINKED ISSUE #5519: [Bug]: Switching between rich text components to fast, causes Microsoft.JSInterop.JSException
### Blazorise Version

1.5.1

### What Blazorise provider are you running on?

Bootstrap5

### Link to minimal reproduction or a simple code snippet

Make two components that have one or more rich text editor components. 
Create a way to switch between te two. 
If you switch fast enough the eroor will be displayed

### Steps to reproduce

//

### What is expected?

It should not cause an error

### What is actually happening?

In richtextedit.json line 120, editorRef is null before it's called. Because you switch before it loaded fully, it causes an error.

Microsoft.JSInterop.JSException: Cannot read properties of null (reading 'quill')
TypeError: Cannot read properties of null (reading 'quill')
    at Module.setReadOnly (https://localhost:7207/_content/Blazorise.RichTextEdit/richtextedit.js?v=1.5.1.0:123:30)
    at https://localhost:7207/_framework/blazor.server.js:1:3506
    at new Promise (<anonymous>)
    at Ft.beginInvokeJSFromDotNet (https://localhost:7207/_framework/blazor.server.js:1:3480)
    at Ft._invokeClientMethod (https://localhost:7207/_framework/blazor.server.js:1:75072)
    at Ft._processIncomingData (https://localhost:7207/_framework/blazor.server.js:1:72696)
    at Ft.connection.onreceive (https://localhost:7207/_framework/blazor.server.js:1:67009)
    at i.onmessage (https://localhost:7207/_framework/blazor.server.js:1:51322)
   at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
   at Microsoft.JSInterop.JSObjectReferenceExtensions.InvokeVoidAsync(IJSObjectReference jsObjectReference, String identifier, Object[] args)
   at Blazorise.Modules.BaseJSModule.InvokeSafeVoidAsync(String identifier, Object[] args)
   at Blazorise.RichTextEdit.RichTextEdit.<>c__DisplayClass15_0.<<SetReadOnly>b__1>d.MoveNext()

### What browsers do you see the problem on?

Microsoft Edge

### Any additional comments?

This bug has been happening for multiple versions of blazorize

### LINKED ISSUE #5604: [Bug]: JSException from Blazorise modal
### Blazorise Version

1.5.2

### What Blazorise provider are you running on?

Material

### Link to minimal reproduction or a simple code snippet

No clear repro scenario found

### Steps to reproduce

From time to time I see the following exception in the Blazor server logs of our app. When it happens the website stops working and needs a forced reload.

```
Microsoft.JSInterop.JSException: Cannot read properties of null (reading 'querySelector')
TypeError: Cannot read properties of null (reading 'querySelector')
    at Module.open (https://xxxx.com/_content/Blazorise.Material/modal.js?v=1.5.2.0:7:35)
    at https://xyz.com/_framework/blazor.server.js:1:3244
    at new Promise (<anonymous>)
    at y.beginInvokeJSFromDotNet (https://zyx.com/_framework/blazor.server.js:1:3201)
    at Xt._invokeClientMethod (https://xxx.com/_framework/blazor.server.js:1:61001)
    at Xt._processIncomingData (https:/xxxx.com/_framework/blazor.server.js:1:58476)
    at Xt.connection.onreceive (https://xxxx.com/_framework/blazor.server.js:1:52117)
    at s.onmessage (https://xxx.com/_framework/blazor.server.js:1:80262)
   at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
   at Microsoft.JSInterop.JSObjectReferenceExtensions.InvokeVoidAsync(IJSObjectReference jsObjectReference, String identifier, Object[] args)
   at Blazorise.Modules.BaseJSModule.InvokeSafeVoidAsync(String identifier, Object[] args)
   at Blazorise.Modal.<HandleVisibilityStyles>b__24_0()
   at Blazorise.BaseAfterRenderComponent.OnAfterRenderAsync(Boolean firstRender)
   at Blazorise.BaseComponent.OnAfterRenderAsync(Boolean firstRender)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
```

### PR DESCRIPTION
**Pull request by David-Moreira**
Closes #5604
Closes #5519
Closes #5175
Closes #4723

### CODE REVIEW

**Comment by David-Moreira** [comment]
Here's the example that you've asked... 
The idea is to change some centralized js invokation and make it call either the old safe or the new safe.

We need to propagate the Blazorise options so I made a temporary class just so I didn't need to change alot of classes.

It's just a matter of 
- Naming the centralized calls, I would name them differently then `InvokeSafeVoidAsync`
  - Maybe `InvokeBaseVoidAsync`?
- Create new `InvokeSafeVoidAsync` method that catches all exceptions.
- Create new `InvokeDefaultVoidAsync` that catches `( exc is JSDisconnectedException or ObjectDisposedException or TaskCanceledException )`
- `if (options.SafeJsInvoke) { InvokeSafeVoidAsync(); //Trully safe now! } else { InvokeDefaultVoidAsync(); }`

Or just leave the long winded code since it's just two base calls and there's no maintainability concern.

**Review by stsrki — COMMENTED** [review]
Sorry it took so long. The changes looks good to me. You can proceed and apply it to all codebase in case there is anything left.

**Comment by David-Moreira** [comment]
> Sorry it took so long. The changes looks good to me. You can proceed and apply it to all codebase in case there is anything left.

Do you prefer **1 or 2**?
image

**Comment by stsrki** [comment]
Do it like you have already started in this PR.

**Comment by stsrki** [comment]
PS. Should this also be fixed with this PR? 

https://blazorise.com/support/issues/156/jsbuttonmodule-throws-an-jsexception-when-reloading-f5-the-page-hosted-in-webview2

**Comment by David-Moreira** [comment]
> PS. Should this also be fixed with this PR?
> 
> https://blazorise.com/support/issues/156/jsbuttonmodule-throws-an-jsexception-when-reloading-f5-the-page-hosted-in-webview2

Yes I believe all of those will be tackled since we'll be try/catching all

**Review by stsrki — APPROVED** [review]

**Pull request merged**
