### PR TITLE
Fix typo in PageButtonContext.PageNumer

### PR DESCRIPTION
**Pull request by WolfgangKluge**
At least I think it's a typo ;)

### CODE REVIEW

**Comment by stsrki** [comment]
It is a typo. But the problem now is, is this a breaking change? We're changing the API so by the definition it should go into v2.

@David-Moreira

**Comment by WolfgangKluge** [comment]
That's definitely a breaking change.

(I think I don't get the version number for the branch name right)

**Comment by stsrki** [comment]
Branching is done like:

- All hotfixes are done from and onto the `rel-1.0.0` branch
- All new development is done onto the `master`

---

I think it is best to open a new issue and schedule this change for v2.0. I hate it but we don't have much choice or we'll break semver rules.

**Comment by stsrki** [comment]
@WolfgangKluge Thanks for the work but it needs to be done 😔

Closing in favor of #3694

**Pull request closed without merging**
