### PR TITLE
Update bug_report.yaml

### LINKED ISSUE #5822: GitHub template for bug report
This would simplify the process of creating bug report repositories for users significantly.

I’m suggesting a repository under `Blazorise/BugReportProject`, which would host a basic Blazor project pre-configured with Blazorise. This repository would function as a [GitHub template](https://docs.github.com/en/repositories/creating-and-managing-repositories/creating-a-template-repository). A GitHub template adds a green "Use template" button at the top, allowing users to create a copy similar to a fork, but without linking to the base repository and with the ability to choose a custom name. It’s quite convenient.

Instructions could be included in the repository's README, and we could reference it in the GitHub issue template (https://docs.github.com/en/repositories/creating-and-managing-repositories/creating-a-template-repository).

Additionally, we could set up a GitHub Action to keep the `BugReportProject` updated with the latest version, minimizing maintenance effort.

### PR DESCRIPTION
**Pull request by tesar-tech**
## Description

Closes #5822

- Multiple bug report repositories were created, one for each provider, with a central hub available [here](https://github.com/Blazorise/BugReportTemplate). The automation is managed by a [GitHub Action](https://github.com/Blazorise/BugReportTemplate/blob/main/.github/workflows/build-template.yml).
  
- For each provider, the action uses `Blazorise.Templates` to generate fresh, up-to-date code.
- It pushes the generated code to the corresponding Bug Report repository (e.g., [BugReportBootstrap5](https://github.com/Blazorise/BugReportBootstrap5)). (so the provider repos are "orphaned")
- Additionally, it copies the README, license, and `.gitignore` files to each repository.
- The README provides basic instructions on how to use the template.
- The action runs daily to:
  - Ensure unique names for each repository (with MMdd suffix), helping us avoid duplicate .NET project names.
  - Keep all repositories up-to-date by using the latest `-f` flag and installing the newest `Blazorise.Templates` version.

### CODE REVIEW

**Review by David-Moreira — APPROVED** [review]
A good addition might be to generate these repositories with their GH action that automatically runs the dotnet build pipeline. This will also have the additional benefit that we make sure that the generated templates build successfully.

Other then the suggestion, LGTM.

**Comment by tesar-tech** [comment]
I am not sure I understand the suggestion. 

- the repositories are generated - not in their own action, but in the `BugReportTemplate` action. What would be the benefit to do it in their own gh actions?
- I can also add the `dotnet build` into the `BugReportTemplate` action. But I don't find it necessary - I somehow trust the `Blazorise.Template` will produce "buildable" repo. The right place to test this is on the `Blazorise.Template` side (but I understand the reality and this is really one line of code to add).

**Comment by stsrki** [comment]
Might be good to also update label action and mention that they can use new project template for reproducible.

https://github.com/Megabit/Blazorise/blob/master/.github/label-actions.yml

**Review by stsrki — APPROVED** [review]

**Comment by David-Moreira** [comment]
> I am not sure I understand the suggestion.
> 
> * the repositories are generated - not in their own action, but in the `BugReportTemplate` action. What would be the benefit to do it in their own gh actions?
> * I can also add the `dotnet build` into the `BugReportTemplate` action. But I don't find it necessary - I somehow trust the `Blazorise.Template` will produce "buildable" repo. The right place to test this is on the `Blazorise.Template` side (but I understand the reality and this is really one line of code to add).

No I meant the second option.
It was just a double check, no harm I guess. But you're right about the right place to making sure **Blazorise.Template** is working correctly is on its own repository.

**Pull request merged**
