### PR TITLE
Icons: Re-use the statically typed names

### LINKED ISSUE #4465: Icon Providers mapping - Re-use the staticly typed names
Example : 
image

image

(Might be faster to implement a script that looks at both and spits out the new mapping)

### PR DESCRIPTION
**Pull request by denis-ivanov**
Closes #4465

### CODE REVIEW

**Comment by denis-ivanov** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by stsrki — COMMENTED** [review]
@denis-ivanov Thanks for the contribution.  Looks good to me.

@David-Moreira do you have any comment?

**Review by David-Moreira — APPROVED** [review]
From a brief look everything seems to match like before. LGTM.

**Comment by David-Moreira** [comment]
The commit seems to not be correctly authored in order for the CLA to be successfully signed.

**Comment by stsrki** [comment]
> The commit seems to not be correctly authored in order for the CLA to be successfully signed.

We have too much problems with the current CLA pipeline. Can we find an alternative? Maybe https://github.com/apps/cla-bot

**Comment by David-Moreira** [comment]
> > The commit seems to not be correctly authored in order for the CLA to be successfully signed.
> 
> We have too many problems with the current CLA pipeline. Can we find an alternative? Maybe https://github.com/apps/cla-bot

What's the problem? The user has a commit which does not identify his github user properly. 
We cannot properly validate the CLA and track all the commits to the same user. It could be someone else that committed for that matter.

image

VS

image

**Comment by denis-ivanov** [comment]
Fixed.

**Comment by David-Moreira** [comment]
> Fixed.

Thanks, appreciated for taking the time.

**Review by stsrki — APPROVED** [review]

**Comment by stsrki** [comment]
Once again, thank you for your contribution. We appreciate it :)

**Pull request merged**
