### PR TITLE
fix some spelling

### PR DESCRIPTION
**Pull request by SimonCropp**

### CODE REVIEW

**Comment by stsrki** [comment]
You're on a roll :) Thank you!

Looks good to me. Still need to review other PRs.

**Comment by stsrki** [comment]
@SimonCropp Did you used any VS Extension for fixing spelling? I hope you didn't go manually through the code :D

**Comment by SimonCropp** [comment]
i have a variety of tools and addins i use to clean up codebases. in this case R# allows u to do a search for all spelling errors

**Comment by stsrki** [comment]
@SimonCropp Hey, you name what extension you use? Thanks

**Comment by SimonCropp** [comment]
@stsrki  resharper does this OOTB

**Pull request merged**
